server:
  port: 10083
spring:
  datasource:
    url: jdbc:postgresql://auth-postgres:25432/auth_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
    open-in-view: false
        
#  security:
#    oauth2:
#      client:
#        registration:
#          custom-test:
#            client-id: clientapp
#            client-secret: 123
#            authorization-grant-type: password
#        provider:
#          custom-test:
#            authorization-uri: https://127.0.0.1:10083/oauth2/v1/authorize
#            token-uri: https://127.0.0.1:10083/oauth2/v1/token
#            user-info-uri: https://127.0.0.1:10083/oauth2/v1/userinfo
#            jwk-set-uri: https://127.0.0.1:10083/oauth2/v1/keys